# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development
 
resources:
  repositories:
   - repository: backend
     type: git
     name: Lenovo-Backend
     ref: development
     
pool:
  name: Dev

steps:

# Checkout repos
- checkout: self
- checkout: backend


# FRONTEND BUILD


- script: |
    echo $(Build.SourcesDirectory)
    pwd
    ls
    cd $(Build.SourcesDirectory)/Lenevo-Frontend
    npm install
  displayName: "Install Frontend Dependencies"
- script: |
    cd $(Build.SourcesDirectory)/Lenevo-Frontend
    npm run build
  displayName: "Build Frontend"

# FRONTEND DOCKER BUILD


- script: |
    cd $(Build.SourcesDirectory)/Lenevo-Frontend
    cp nginx.dev.conf nginx.active.conf
    docker build -t lenovo-frontend:$(Build.BuildId) .
  displayName: "Build Frontend Docker Image"


# BACKEND DOCKER BUILD


- script: |
    cd $(Build.SourcesDirectory)/Lenovo-Backend

    docker build -t lenovo-backend:$(Build.BuildId) .
  displayName: "Build Backend Docker Image"

# VERIFY IMAGES


- script: |
    docker images
  displayName: "Verify Docker Images"


# CREATE NETWORK IF NOT EXISTS
- script: |
    docker network inspect lenovo-net >/dev/null 2>&1 || docker network create lenovo-net
  displayName: 'Create Docker Network'

# DEPLOY BACKEND
- script: |
    docker stop lenovo-aibackend || true
    docker rm lenovo-aibackend || true

    docker run -d \
      --restart unless-stopped \
      --name lenovo-aibackend \
      --network lenovo-net \
      -p 9100:9100 \
      lenovo-backend:$(Build.BuildId)
  displayName: 'Deploy Backend'

# DEPLOY FRONTEND
- script: |
    docker stop frontend || true
    docker rm frontend || true

    docker run -d \
      --restart unless-stopped \
      --name frontend \
      --network lenovo-net \
      -p 80:80 \
      lenovo-frontend:$(Build.BuildId)
  displayName: 'Deploy Frontend'

# VERIFY
- script: |
    docker ps

    echo "===== BACKEND LOGS ====="
    docker logs lenovo-aibackend 

    echo "===== FRONTEND LOGS ====="
    docker logs frontend 
  displayName: 'Verify Deployment'
